# Generated by Django 4.2.13 on 2024-05-21 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('request_method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=200)),
                ('request_headers', models.TextField()),
                ('response_status', models.IntegerField()),
                ('response_headers', models.TextField()),
                ('response_body', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
