# Generated by Django 4.2.13 on 2024-05-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedlog',
            name='is_malicious',
            field=models.BooleanField(default=False),
        ),
    ]
